/* eslint-disable react-hooks/exhaustive-deps */
import { useState, useEffect } from 'react';
import img1 from '../../assets/images/img_4.jpg';
import img2 from '../../assets/images/img_5.jpg';
import img3 from '../../assets/images/img_6.jpg';
import img4 from '../../assets/images/img_7.jpg';
import trainImg1 from '../../assets/images/train_img_3.jpg';
import trainImg2 from '../../assets/images/train_img_5.jpg';
import trainImg3 from '../../assets/images/train_img_4.jpg';
import trainImg4 from '../../assets/images/train_img_2.jpg';
import airplaneImg1 from '../../assets/images/airplane_img_3.jpg';
import airplaneImg2 from '../../assets/images/airplane_img_1.jpg';
import airplaneImg3 from '../../assets/images/airplane_img_5.jpg';
import airplaneImg4 from '../../assets/images/airplane_img_4.jpg';
import launchImg1 from '../../assets/images/launch_img_1.jpg';
import launchImg2 from '../../assets/images/launch_img_2.jpg';
import launchImg3 from '../../assets/images/launch_img_4.jpg';
import launchImg4 from '../../assets/images/launch_img_3.jpeg';
import "../../App.css"

const Blog = () => {
    const [slideIndex, setSlideIndex] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setSlideIndex((prevIndex) => (prevIndex + 1) % 16);
        }, 3000); // Change image every 5 seconds

        return () => clearInterval(interval);
    }, []);

    const slides = [
        { src: img1, alt: 'Slide 1', type: 'bus', content: "Dhaka, the vibrant heart of Bangladesh, relies heavily on its intricate bus service network to facilitate the daily movement of its vast population. The city's bus system is a vital cog in its transportation machinery, serving as a primary mode of travel for millions of residents and commuters. Dhaka's bus fleet is diverse, ranging from traditional, colorful double-decker buses to modern, air-conditioned coaches, catering to the diverse needs of passengers. Despite grappling with challenges like traffic congestion and inadequate infrastructure, the city's bus service perseveres, providing an essential lifeline for citizens navigating its bustling streets. From bustling business districts to serene residential neighborhoods, Dhaka's buses traverse every corner, linking communities and enabling access to essential services, education, and employment opportunities. As Dhaka continues to evolve and grow, its bus service remains a vital artery, ensuring the city remains connected and accessible to all." },
        { src: img2, alt: 'Slide 2', type: 'bus', content: "Dhaka, the vibrant heart of Bangladesh, relies heavily on its intricate bus service network to facilitate the daily movement of its vast population. The city's bus system is a vital cog in its transportation machinery, serving as a primary mode of travel for millions of residents and commuters. Dhaka's bus fleet is diverse, ranging from traditional, colorful double-decker buses to modern, air-conditioned coaches, catering to the diverse needs of passengers. Despite grappling with challenges like traffic congestion and inadequate infrastructure, the city's bus service perseveres, providing an essential lifeline for citizens navigating its bustling streets. From bustling business districts to serene residential neighborhoods, Dhaka's buses traverse every corner, linking communities and enabling access to essential services, education, and employment opportunities. As Dhaka continues to evolve and grow, its bus service remains a vital artery, ensuring the city remains connected and accessible to all." },
        { src: img3, alt: 'Slide 2', type: 'bus', content: "Dhaka, the vibrant heart of Bangladesh, relies heavily on its intricate bus service network to facilitate the daily movement of its vast population. The city's bus system is a vital cog in its transportation machinery, serving as a primary mode of travel for millions of residents and commuters. Dhaka's bus fleet is diverse, ranging from traditional, colorful double-decker buses to modern, air-conditioned coaches, catering to the diverse needs of passengers. Despite grappling with challenges like traffic congestion and inadequate infrastructure, the city's bus service perseveres, providing an essential lifeline for citizens navigating its bustling streets. From bustling business districts to serene residential neighborhoods, Dhaka's buses traverse every corner, linking communities and enabling access to essential services, education, and employment opportunities. As Dhaka continues to evolve and grow, its bus service remains a vital artery, ensuring the city remains connected and accessible to all." },
        { src: img4, alt: 'Slide 2', type: 'bus', content: "Dhaka, the vibrant heart of Bangladesh, relies heavily on its intricate bus service network to facilitate the daily movement of its vast population. The city's bus system is a vital cog in its transportation machinery, serving as a primary mode of travel for millions of residents and commuters. Dhaka's bus fleet is diverse, ranging from traditional, colorful double-decker buses to modern, air-conditioned coaches, catering to the diverse needs of passengers. Despite grappling with challenges like traffic congestion and inadequate infrastructure, the city's bus service perseveres, providing an essential lifeline for citizens navigating its bustling streets. From bustling business districts to serene residential neighborhoods, Dhaka's buses traverse every corner, linking communities and enabling access to essential services, education, and employment opportunities. As Dhaka continues to evolve and grow, its bus service remains a vital artery, ensuring the city remains connected and accessible to all." },
        { src: trainImg1, alt: 'Slide 3', type: 'train', content: "Embarking on Bangladesh's newly launched metro rail system unfolds a transformative journey through the heart of urban connectivity. With the inauguration of the country's first metro lines, Bangladesh marks a significant milestone in its transportation infrastructure. From the vibrant streets of Dhaka to the bustling neighborhoods of Gazipur, these sleek trains signify a leap forward in modern transportation. They offer a swift and efficient mode of travel, easing congestion on the roads and providing a sustainable alternative for commuters. As the metro lines crisscross the cityscape, they connect key destinations, facilitating seamless movement within the capital region. Challenges such as ensuring operational efficiency and maintaining safety standards loom large, yet the potential for easing urban congestion and enhancing the quality of life is undeniable. As Bangladesh embraces the era of metro rail, these trains emerge as engines of progress, propelling the nation toward a future where mobility knows no bounds and opportunity awaits at every station." },
        { src: trainImg2, alt: 'Slide 3', type: 'train', content: "Embarking on Bangladesh's newly launched metro rail system unfolds a transformative journey through the heart of urban connectivity. With the inauguration of the country's first metro lines, Bangladesh marks a significant milestone in its transportation infrastructure. From the vibrant streets of Dhaka to the bustling neighborhoods of Gazipur, these sleek trains signify a leap forward in modern transportation. They offer a swift and efficient mode of travel, easing congestion on the roads and providing a sustainable alternative for commuters. As the metro lines crisscross the cityscape, they connect key destinations, facilitating seamless movement within the capital region. Challenges such as ensuring operational efficiency and maintaining safety standards loom large, yet the potential for easing urban congestion and enhancing the quality of life is undeniable. As Bangladesh embraces the era of metro rail, these trains emerge as engines of progress, propelling the nation toward a future where mobility knows no bounds and opportunity awaits at every station." },
        { src: trainImg3, alt: 'Slide 3', type: 'train', content: "Embarking on Bangladesh's newly launched metro rail system unfolds a transformative journey through the heart of urban connectivity. With the inauguration of the country's first metro lines, Bangladesh marks a significant milestone in its transportation infrastructure. From the vibrant streets of Dhaka to the bustling neighborhoods of Gazipur, these sleek trains signify a leap forward in modern transportation. They offer a swift and efficient mode of travel, easing congestion on the roads and providing a sustainable alternative for commuters. As the metro lines crisscross the cityscape, they connect key destinations, facilitating seamless movement within the capital region. Challenges such as ensuring operational efficiency and maintaining safety standards loom large, yet the potential for easing urban congestion and enhancing the quality of life is undeniable. As Bangladesh embraces the era of metro rail, these trains emerge as engines of progress, propelling the nation toward a future where mobility knows no bounds and opportunity awaits at every station." },
        { src: trainImg4, alt: 'Slide 3', type: 'train', content: "Embarking on Bangladesh's newly launched metro rail system unfolds a transformative journey through the heart of urban connectivity. With the inauguration of the country's first metro lines, Bangladesh marks a significant milestone in its transportation infrastructure. From the vibrant streets of Dhaka to the bustling neighborhoods of Gazipur, these sleek trains signify a leap forward in modern transportation. They offer a swift and efficient mode of travel, easing congestion on the roads and providing a sustainable alternative for commuters. As the metro lines crisscross the cityscape, they connect key destinations, facilitating seamless movement within the capital region. Challenges such as ensuring operational efficiency and maintaining safety standards loom large, yet the potential for easing urban congestion and enhancing the quality of life is undeniable. As Bangladesh embraces the era of metro rail, these trains emerge as engines of progress, propelling the nation toward a future where mobility knows no bounds and opportunity awaits at every station." },
        { src: launchImg2, alt: 'Slide 6', type: 'launch', content: "Exploring Bangladesh's burgeoning waterways unveils a narrative of connectivity and potential. With its vast network of rivers, canals, and water bodies, Bangladesh has long relied on water transport for trade and commerce. The recent launch of waterway services marks a significant step forward, enhancing connectivity between urban centers and rural communities. From bustling river ports to tranquil waterfronts, these services promise to revolutionize transportation, providing efficient and eco-friendly alternatives to roadways. Challenges such as infrastructure development and safety concerns must be addressed, yet opportunities for growth and innovation abound. As Bangladesh navigates toward a future shaped by progress and sustainability, its waterway services emerge as vital arteries, uniting the nation and fostering economic development. In this dynamic landscape, the promise of tomorrow sets sail, charting a course where the waters teem with possibility and the spirit of exploration flows freely." },
        { src: launchImg1, alt: 'Slide 6', type: 'launch', content: "Exploring Bangladesh's burgeoning waterways unveils a narrative of connectivity and potential. With its vast network of rivers, canals, and water bodies, Bangladesh has long relied on water transport for trade and commerce. The recent launch of waterway services marks a significant step forward, enhancing connectivity between urban centers and rural communities. From bustling river ports to tranquil waterfronts, these services promise to revolutionize transportation, providing efficient and eco-friendly alternatives to roadways. Challenges such as infrastructure development and safety concerns must be addressed, yet opportunities for growth and innovation abound. As Bangladesh navigates toward a future shaped by progress and sustainability, its waterway services emerge as vital arteries, uniting the nation and fostering economic development. In this dynamic landscape, the promise of tomorrow sets sail, charting a course where the waters teem with possibility and the spirit of exploration flows freely." },
        { src: launchImg3, alt: 'Slide 6', type: 'launch', content: "Exploring Bangladesh's burgeoning waterways unveils a narrative of connectivity and potential. With its vast network of rivers, canals, and water bodies, Bangladesh has long relied on water transport for trade and commerce. The recent launch of waterway services marks a significant step forward, enhancing connectivity between urban centers and rural communities. From bustling river ports to tranquil waterfronts, these services promise to revolutionize transportation, providing efficient and eco-friendly alternatives to roadways. Challenges such as infrastructure development and safety concerns must be addressed, yet opportunities for growth and innovation abound. As Bangladesh navigates toward a future shaped by progress and sustainability, its waterway services emerge as vital arteries, uniting the nation and fostering economic development. In this dynamic landscape, the promise of tomorrow sets sail, charting a course where the waters teem with possibility and the spirit of exploration flows freely." },
        { src: launchImg4, alt: 'Slide 6', type: 'launch', content: "Exploring Bangladesh's burgeoning waterways unveils a narrative of connectivity and potential. With its vast network of rivers, canals, and water bodies, Bangladesh has long relied on water transport for trade and commerce. The recent launch of waterway services marks a significant step forward, enhancing connectivity between urban centers and rural communities. From bustling river ports to tranquil waterfronts, these services promise to revolutionize transportation, providing efficient and eco-friendly alternatives to roadways. Challenges such as infrastructure development and safety concerns must be addressed, yet opportunities for growth and innovation abound. As Bangladesh navigates toward a future shaped by progress and sustainability, its waterway services emerge as vital arteries, uniting the nation and fostering economic development. In this dynamic landscape, the promise of tomorrow sets sail, charting a course where the waters teem with possibility and the spirit of exploration flows freely." },
        { src: airplaneImg1, alt: 'Slide 7', type: 'airplane', content: "Discovering Bangladesh's domestic airline sector unveils a narrative of evolution and connectivity. Since its inception in the 1970s with Biman Bangladesh Airlines, the industry has flourished, with carriers like Novoair, US-Bangla Airlines, and Regent Airways joining the ranks. Facilitating travel between bustling metropolises and remote corners, these airlines play a pivotal role in uniting the nation. However, challenges loom, from infrastructure limitations to pandemic-induced setbacks. Yet, amidst these hurdles, opportunities emerge for innovation and collaboration. Modernizing infrastructure, embracing technology, and enhancing safety standards are imperative for sustained growth. As Bangladesh propels toward a future defined by progress, its domestic airlines stand as symbols of resilience, carrying the aspirations of millions skyward. In this ever-changing landscape, the promise of tomorrow fuels the industry's journey, charting a course where the skies know no bounds and the spirit of exploration soars." },
        { src: airplaneImg2, alt: 'Slide 8', type: 'airplane', content: "Discovering Bangladesh's domestic airline sector unveils a narrative of evolution and connectivity. Since its inception in the 1970s with Biman Bangladesh Airlines, the industry has flourished, with carriers like Novoair, US-Bangla Airlines, and Regent Airways joining the ranks. Facilitating travel between bustling metropolises and remote corners, these airlines play a pivotal role in uniting the nation. However, challenges loom, from infrastructure limitations to pandemic-induced setbacks. Yet, amidst these hurdles, opportunities emerge for innovation and collaboration. Modernizing infrastructure, embracing technology, and enhancing safety standards are imperative for sustained growth. As Bangladesh propels toward a future defined by progress, its domestic airlines stand as symbols of resilience, carrying the aspirations of millions skyward. In this ever-changing landscape, the promise of tomorrow fuels the industry's journey, charting a course where the skies know no bounds and the spirit of exploration soars." },
        { src: airplaneImg3, alt: 'Slide 8', type: 'airplane', content: "Discovering Bangladesh's domestic airline sector unveils a narrative of evolution and connectivity. Since its inception in the 1970s with Biman Bangladesh Airlines, the industry has flourished, with carriers like Novoair, US-Bangla Airlines, and Regent Airways joining the ranks. Facilitating travel between bustling metropolises and remote corners, these airlines play a pivotal role in uniting the nation. However, challenges loom, from infrastructure limitations to pandemic-induced setbacks. Yet, amidst these hurdles, opportunities emerge for innovation and collaboration. Modernizing infrastructure, embracing technology, and enhancing safety standards are imperative for sustained growth. As Bangladesh propels toward a future defined by progress, its domestic airlines stand as symbols of resilience, carrying the aspirations of millions skyward. In this ever-changing landscape, the promise of tomorrow fuels the industry's journey, charting a course where the skies know no bounds and the spirit of exploration soars." },
        { src: airplaneImg4, alt: 'Slide 8', type: 'airplane', content: "Discovering Bangladesh's domestic airline sector unveils a narrative of evolution and connectivity. Since its inception in the 1970s with Biman Bangladesh Airlines, the industry has flourished, with carriers like Novoair, US-Bangla Airlines, and Regent Airways joining the ranks. Facilitating travel between bustling metropolises and remote corners, these airlines play a pivotal role in uniting the nation. However, challenges loom, from infrastructure limitations to pandemic-induced setbacks. Yet, amidst these hurdles, opportunities emerge for innovation and collaboration. Modernizing infrastructure, embracing technology, and enhancing safety standards are imperative for sustained growth. As Bangladesh propels toward a future defined by progress, its domestic airlines stand as symbols of resilience, carrying the aspirations of millions skyward. In this ever-changing landscape, the promise of tomorrow fuels the industry's journey, charting a course where the skies know no bounds and the spirit of exploration soars." },
        
    ];

    return (
        <div className="bg-zinc-900 min-h-screen flex flex-col justify-center items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#000" fillOpacity="1" d="M0,320L30,309.3C60,299,120,277,180,245.3C240,213,300,171,360,165.3C420,160,480,192,540,213.3C600,235,660,245,720,250.7C780,256,840,256,900,240C960,224,1020,192,1080,181.3C1140,171,1200,181,1260,208C1320,235,1380,277,1410,298.7L1440,320L1440,0L1410,0C1380,0,1320,0,1260,0C1200,0,1140,0,1080,0C1020,0,960,0,900,0C840,0,780,0,720,0C660,0,600,0,540,0C480,0,420,0,360,0C300,0,240,0,180,0C120,0,60,0,30,0L0,0Z"></path></svg>
            
            
            <h1 className="text-4xl text-white font-bold text-center pb-10">Blog Section</h1>
            {slides.map((slide, index) => (
                <section
                    key={index}
                    className={`flex py-5 mx-10 mb-9 w-full ${index === slideIndex ? '' : 'hidden'}`}
                >
                    <div className="w-3/5 px-24 mt-16">
                        <h1 className="text-3xl font-semibold text-white pb-3">{slide.type === 'bus' ? 'Bus' : slide.type === 'train' ? 'Metro Rail' : slide.type === 'airplane' ? 'Domestic Airplane' : 'Launch'}</h1>
                        <p className="text-white text-justify">
                            {slide.content}
                        </p>
                    </div>
                    <div className="w-2/5 h-[500px]">
                        <div className="relative h-[520px] w-[500px] max-w-screen-lg mx-auto">
                            <img
                                src={slide.src}
                                alt={slide.alt}
                                className="object-cover rounded-2xl w-full h-full"
                            />
                        </div>
                    </div>
                </section>
            ))}
        </div>
    );
};

export default Blog;
